#ifndef MANA_BUILDOPTIMIZATION_HPP
#define MANA_BUILDOPTIMIZATION_HPP

enum BuildOptimization {
    NONE,
    OPTIMIZE_ONE,
    OPTIMIZE_TWO,
    OPTIMIZE_THREE,
    OPTIMIZE_SIZE
};

#endif //MANA_BUILDOPTIMIZATION_HPP
